#!/usr/bin/env deno run -A
// vi:syntax=javascript
import parse from "./parser-2.1.3.js"

const decoder = new TextDecoder("utf-8");
const path = Deno.cwd() + '/app.arc'
const raw = await Deno.readFile(path)
const arc = parse(decoder.decode(raw))
const allowed = arc.begin.map(line=> line[0]) 
const command = Deno.args[0];
const tuple = arc.begin.find(line=> line[0] === command)
const value = Array.isArray(tuple)? tuple[1] : false

if (allowed.includes(command)) {
  const p = Deno.run({ env: {DENO_ENV:'testing'}, cmd: value.split(" ") });
  const { code } = await p.status();

  if (code != 0) {
    const rawError = await p.stderrOutput();
    const errorString = new TextDecoder().decode(rawError);
    console.log(errorString);
  }

  Deno.exit(code);
} else {
  console.log(`error: unknown command "${command}"`);
  console.log(`allowed: ${allowed.join(", ")}`);
}
